"""Curated knowledge base of medicinal plants, with MENA provenance.

Each entry describes one plant (usually at species level, occasionally genus) and
carries enough naming variants to be recognised in the messy free text of a
title / abstract / keyword field:

* ``scientific``  — accepted binomial (or genus) used as the canonical id.
* ``synonyms``    — botanical synonyms and older names still common in the literature.
* ``common``      — English common names and transliterated Arabic/Persian/Turkish
                    names actually used in MENA ethnobotanical papers.
* ``family``      — plant family.
* ``mena``        — ``True`` when the plant is native to, or has a deep traditional
                    medicinal history in, the Middle East / North Africa region.
* ``regions``     — coarse provenance tags (informational).
* ``uses``        — well-documented pharmacological activities (canonical activity
                    labels from ``knowledge.activities``). This is *reference*
                    knowledge only — the classifier still reads activities from the
                    paper text so it never invents claims a paper did not make.

The list intentionally also contains widely-studied *non*-MENA medicinal plants
(turmeric, ginger, ashwagandha, ginkgo…) flagged ``mena=False`` so the app can
correctly answer "is this a MENA plant?" with *no* as well as *yes*.
"""
from __future__ import annotations

# Region tags (informational, not exhaustive).
MENA = "MENA"
MED = "Mediterranean"
IRAN = "Irano-Turanian"
ARABIA = "Arabian Peninsula"
NAFRICA = "North Africa"
LEVANT = "Levant"
GLOBAL = "Cosmopolitan"

PLANTS: list[dict] = [
    # ---- Signature MENA medicinal plants -------------------------------------
    {
        "scientific": "Nigella sativa",
        "synonyms": ["Nigella cretica"],
        "common": ["black seed", "black cumin", "black caraway", "kalonji",
                   "habbat al-barakah", "habba sawda", "habbatul barakah", "shonaiz"],
        "family": "Ranunculaceae",
        "mena": True,
        "regions": [MENA, MED, LEVANT],
        "uses": ["Antidiabetic", "Anticancer/Antitumor", "Anti-inflammatory",
                 "Antioxidant", "Antimicrobial", "Immunomodulatory", "Hepatoprotective"],
    },
    {
        "scientific": "Trigonella foenum-graecum",
        "synonyms": ["Trigonella foenum graecum"],
        "common": ["fenugreek", "hulba", "helba", "methi", "shanbalileh"],
        "family": "Fabaceae",
        "mena": True,
        "regions": [MENA, MED, IRAN],
        "uses": ["Antidiabetic", "Antihyperlipidemic", "Anti-inflammatory", "Galactagogue"],
    },
    {
        "scientific": "Peganum harmala",
        "synonyms": [],
        "common": ["Syrian rue", "harmal", "harmel", "esfand", "wild rue"],
        "family": "Nitrariaceae",
        "mena": True,
        "regions": [MENA, IRAN, ARABIA],
        "uses": ["Anticancer/Antitumor", "Antimicrobial", "Antileishmanial",
                 "Neuroprotective", "Antidepressant/Anxiolytic"],
    },
    {
        "scientific": "Rhazya stricta",
        "synonyms": [],
        "common": ["harmal", "hanzab", "sehar"],
        "family": "Apocynaceae",
        "mena": True,
        "regions": [ARABIA, IRAN],
        "uses": ["Anticancer/Antitumor", "Antidiabetic", "Antimicrobial", "Antioxidant"],
    },
    {
        "scientific": "Ziziphus spina-christi",
        "synonyms": ["Ziziphus spina christi", "Zizyphus spina-christi"],
        "common": ["christ's thorn jujube", "sidr", "nabk", "nabag", "konar"],
        "family": "Rhamnaceae",
        "mena": True,
        "regions": [ARABIA, NAFRICA, LEVANT],
        "uses": ["Antidiabetic", "Antimicrobial", "Antioxidant", "Wound healing", "Anti-inflammatory"],
    },
    {
        "scientific": "Ziziphus jujuba",
        "synonyms": ["Zizyphus jujuba", "Ziziphus vulgaris"],
        "common": ["jujube", "annab", "red date", "chinese date"],
        "family": "Rhamnaceae",
        "mena": True,
        "regions": [IRAN, MED],
        "uses": ["Antioxidant", "Immunomodulatory", "Anti-inflammatory", "Neuroprotective"],
    },
    {
        "scientific": "Olea europaea",
        "synonyms": [],
        "common": ["olive", "olive leaf", "zaytoun", "zeytin"],
        "family": "Oleaceae",
        "mena": True,
        "regions": [MED, MENA],
        "uses": ["Antihypertensive", "Antioxidant", "Antidiabetic", "Antimicrobial",
                 "Anticancer/Antitumor", "Antihyperlipidemic"],
    },
    {
        "scientific": "Punica granatum",
        "synonyms": [],
        "common": ["pomegranate", "rumman", "anar"],
        "family": "Lythraceae",
        "mena": True,
        "regions": [IRAN, MENA, MED],
        "uses": ["Antioxidant", "Anticancer/Antitumor", "Anti-inflammatory",
                 "Antihypertensive", "Antimicrobial"],
    },
    {
        "scientific": "Cuminum cyminum",
        "synonyms": [],
        "common": ["cumin", "kamun", "zeera", "zireh"],
        "family": "Apiaceae",
        "mena": True,
        "regions": [MENA, IRAN, MED],
        "uses": ["Antidiabetic", "Antimicrobial", "Antioxidant", "Gastroprotective/Antiulcer"],
    },
    {
        "scientific": "Foeniculum vulgare",
        "synonyms": [],
        "common": ["fennel", "shamar", "razianeh", "raziyane"],
        "family": "Apiaceae",
        "mena": True,
        "regions": [MED, MENA],
        "uses": ["Antispasmodic", "Antioxidant", "Antimicrobial", "Estrogenic", "Anti-inflammatory"],
    },
    {
        "scientific": "Thymus vulgaris",
        "synonyms": ["Thymus serpyllum", "Thymbra spicata", "Thymus capitatus"],
        "common": ["thyme", "zaatar", "zahtar", "zataria"],
        "family": "Lamiaceae",
        "mena": True,
        "regions": [MED, LEVANT, MENA],
        "uses": ["Antimicrobial", "Antioxidant", "Antifungal", "Anti-inflammatory", "Antispasmodic"],
    },
    {
        "scientific": "Zataria multiflora",
        "synonyms": [],
        "common": ["shirazi thyme", "avishan shirazi", "zataria"],
        "family": "Lamiaceae",
        "mena": True,
        "regions": [IRAN, ARABIA],
        "uses": ["Antimicrobial", "Antifungal", "Antispasmodic", "Anti-inflammatory"],
    },
    {
        "scientific": "Salvia officinalis",
        "synonyms": ["Salvia fruticosa", "Salvia triloba"],
        "common": ["sage", "maryamiya", "maramia", "meramia"],
        "family": "Lamiaceae",
        "mena": True,
        "regions": [MED, LEVANT],
        "uses": ["Antioxidant", "Antidiabetic", "Antimicrobial", "Neuroprotective", "Anti-inflammatory"],
    },
    {
        "scientific": "Rosmarinus officinalis",
        "synonyms": ["Salvia rosmarinus"],
        "common": ["rosemary", "iklil al-jabal", "hasalban"],
        "family": "Lamiaceae",
        "mena": True,
        "regions": [MED, MENA],
        "uses": ["Antioxidant", "Anticancer/Antitumor", "Neuroprotective", "Antimicrobial", "Hepatoprotective"],
    },
    {
        "scientific": "Origanum vulgare",
        "synonyms": ["Origanum syriacum", "Origanum majorana", "Majorana hortensis"],
        "common": ["oregano", "marjoram", "wild thyme", "zaatar barri"],
        "family": "Lamiaceae",
        "mena": True,
        "regions": [MED, LEVANT],
        "uses": ["Antimicrobial", "Antioxidant", "Anti-inflammatory", "Antifungal"],
    },
    {
        "scientific": "Mentha piperita",
        "synonyms": ["Mentha spicata", "Mentha longifolia", "Mentha arvensis"],
        "common": ["mint", "peppermint", "spearmint", "naana", "nana", "pudina"],
        "family": "Lamiaceae",
        "mena": True,
        "regions": [MED, MENA],
        "uses": ["Antispasmodic", "Antimicrobial", "Antioxidant", "Gastroprotective/Antiulcer"],
    },
    {
        "scientific": "Matricaria chamomilla",
        "synonyms": ["Matricaria recutita", "Chamomilla recutita"],
        "common": ["chamomile", "babunaj", "babouneh", "babuneh"],
        "family": "Asteraceae",
        "mena": True,
        "regions": [MED, IRAN],
        "uses": ["Anti-inflammatory", "Antispasmodic", "Antioxidant", "Wound healing", "Antidepressant/Anxiolytic"],
    },
    {
        "scientific": "Artemisia herba-alba",
        "synonyms": ["Artemisia herba alba", "Artemisia absinthium", "Artemisia sieberi"],
        "common": ["white wormwood", "desert wormwood", "shih", "sheeh", "afsantin"],
        "family": "Asteraceae",
        "mena": True,
        "regions": [NAFRICA, MENA, ARABIA],
        "uses": ["Antidiabetic", "Antimalarial", "Antimicrobial", "Anti-inflammatory", "Antioxidant"],
    },
    {
        "scientific": "Teucrium polium",
        "synonyms": [],
        "common": ["felty germander", "jaadeh", "jaideh", "kalpoureh"],
        "family": "Lamiaceae",
        "mena": True,
        "regions": [MED, IRAN, ARABIA],
        "uses": ["Antidiabetic", "Antihyperlipidemic", "Antioxidant", "Anti-inflammatory"],
    },
    {
        "scientific": "Citrullus colocynthis",
        "synonyms": [],
        "common": ["bitter apple", "colocynth", "handhal", "hanzal", "sharri"],
        "family": "Cucurbitaceae",
        "mena": True,
        "regions": [NAFRICA, ARABIA, MENA],
        "uses": ["Antidiabetic", "Anticancer/Antitumor", "Antimicrobial", "Anti-inflammatory"],
    },
    {
        "scientific": "Glycyrrhiza glabra",
        "synonyms": ["Glycyrrhiza uralensis"],
        "common": ["licorice", "liquorice", "sus", "erk al-sus", "shirin bayan"],
        "family": "Fabaceae",
        "mena": True,
        "regions": [IRAN, MED, MENA],
        "uses": ["Anti-inflammatory", "Antiviral", "Gastroprotective/Antiulcer", "Hepatoprotective", "Antimicrobial"],
    },
    {
        "scientific": "Capparis spinosa",
        "synonyms": [],
        "common": ["caper", "kabar", "shafallah", "lassaf"],
        "family": "Capparaceae",
        "mena": True,
        "regions": [MED, MENA, ARABIA],
        "uses": ["Antidiabetic", "Anti-inflammatory", "Antioxidant", "Hepatoprotective"],
    },
    {
        "scientific": "Alhagi maurorum",
        "synonyms": ["Alhagi graecorum", "Alhagi camelorum"],
        "common": ["camel thorn", "aqool", "aqul", "manna", "khar-shotor"],
        "family": "Fabaceae",
        "mena": True,
        "regions": [IRAN, ARABIA, MENA],
        "uses": ["Antioxidant", "Antimicrobial", "Hepatoprotective", "Anti-inflammatory"],
    },
    {
        "scientific": "Ferula assa-foetida",
        "synonyms": ["Ferula asafoetida", "Ferula gummosa", "Ferula communis"],
        "common": ["asafoetida", "asafetida", "hing", "heltit", "anghozeh"],
        "family": "Apiaceae",
        "mena": True,
        "regions": [IRAN, MENA],
        "uses": ["Antispasmodic", "Antimicrobial", "Anticancer/Antitumor", "Antioxidant"],
    },
    {
        "scientific": "Boswellia sacra",
        "synonyms": ["Boswellia carterii", "Boswellia serrata"],
        "common": ["frankincense", "olibanum", "luban", "kundur"],
        "family": "Burseraceae",
        "mena": True,
        "regions": [ARABIA],
        "uses": ["Anti-inflammatory", "Anticancer/Antitumor", "Anti-arthritic", "Immunomodulatory"],
    },
    {
        "scientific": "Commiphora myrrha",
        "synonyms": ["Commiphora molmol"],
        "common": ["myrrh", "murr", "mur"],
        "family": "Burseraceae",
        "mena": True,
        "regions": [ARABIA, NAFRICA],
        "uses": ["Antimicrobial", "Anti-inflammatory", "Analgesic", "Wound healing", "Antiparasitic"],
    },
    {
        "scientific": "Lawsonia inermis",
        "synonyms": [],
        "common": ["henna", "hinna", "hena", "mignonette tree"],
        "family": "Lythraceae",
        "mena": True,
        "regions": [NAFRICA, ARABIA, MENA],
        "uses": ["Antimicrobial", "Antifungal", "Wound healing", "Anticancer/Antitumor", "Antioxidant"],
    },
    {
        "scientific": "Crocus sativus",
        "synonyms": [],
        "common": ["saffron", "zaafaran", "zafaran", "zaffron"],
        "family": "Iridaceae",
        "mena": True,
        "regions": [IRAN, MENA],
        "uses": ["Antidepressant/Anxiolytic", "Anticancer/Antitumor", "Antioxidant", "Neuroprotective", "Cardioprotective"],
    },
    {
        "scientific": "Hibiscus sabdariffa",
        "synonyms": [],
        "common": ["roselle", "karkade", "karkadeh", "hibiscus"],
        "family": "Malvaceae",
        "mena": True,
        "regions": [NAFRICA, MENA],
        "uses": ["Antihypertensive", "Antioxidant", "Antihyperlipidemic", "Antimicrobial"],
    },
    {
        "scientific": "Cichorium intybus",
        "synonyms": [],
        "common": ["chicory", "hindba", "kasni"],
        "family": "Asteraceae",
        "mena": True,
        "regions": [MED, IRAN],
        "uses": ["Hepatoprotective", "Antidiabetic", "Antioxidant", "Anti-inflammatory"],
    },
    {
        "scientific": "Portulaca oleracea",
        "synonyms": [],
        "common": ["purslane", "baqle", "farfahin", "khorfeh", "rijla"],
        "family": "Portulacaceae",
        "mena": True,
        "regions": [MENA, MED, GLOBAL],
        "uses": ["Antioxidant", "Antidiabetic", "Neuroprotective", "Anti-inflammatory", "Hepatoprotective"],
    },
    {
        "scientific": "Aloe vera",
        "synonyms": ["Aloe barbadensis", "Aloe perryi"],
        "common": ["aloe", "sabr", "saber", "sibar"],
        "family": "Asphodelaceae",
        "mena": True,
        "regions": [ARABIA, NAFRICA],
        "uses": ["Wound healing", "Anti-inflammatory", "Antidiabetic", "Antimicrobial", "Antioxidant"],
    },
    {
        "scientific": "Moringa peregrina",
        "synonyms": ["Moringa oleifera"],
        "common": ["moringa", "yasar", "ban", "drumstick tree", "al-yasar"],
        "family": "Moringaceae",
        "mena": True,
        "regions": [ARABIA, NAFRICA],
        "uses": ["Antidiabetic", "Antihyperlipidemic", "Antioxidant", "Anti-inflammatory", "Anticancer/Antitumor"],
    },
    {
        "scientific": "Phoenix dactylifera",
        "synonyms": [],
        "common": ["date palm", "date", "nakhl", "tamr", "ajwa"],
        "family": "Arecaceae",
        "mena": True,
        "regions": [ARABIA, NAFRICA, MENA],
        "uses": ["Antioxidant", "Anti-inflammatory", "Hepatoprotective", "Antidiabetic"],
    },
    {
        "scientific": "Ricinus communis",
        "synonyms": [],
        "common": ["castor", "castor bean", "kharwa", "kherwe"],
        "family": "Euphorbiaceae",
        "mena": True,
        "regions": [NAFRICA, MENA],
        "uses": ["Anti-inflammatory", "Antimicrobial", "Analgesic", "Hepatoprotective", "Larvicidal"],
    },
    {
        "scientific": "Coriandrum sativum",
        "synonyms": [],
        "common": ["coriander", "cilantro", "kuzbara", "kishnij", "geshniz"],
        "family": "Apiaceae",
        "mena": True,
        "regions": [MED, MENA, IRAN],
        "uses": ["Antidiabetic", "Antioxidant", "Antimicrobial", "Anti-inflammatory", "Anxiolytic"],
    },
    {
        "scientific": "Pimpinella anisum",
        "synonyms": [],
        "common": ["anise", "aniseed", "yansoon", "yansun", "anisoon"],
        "family": "Apiaceae",
        "mena": True,
        "regions": [MED, MENA, LEVANT],
        "uses": ["Antispasmodic", "Antimicrobial", "Antioxidant", "Anti-inflammatory"],
    },
    {
        "scientific": "Carum carvi",
        "synonyms": [],
        "common": ["caraway", "karawya", "karaweya", "zireh siah"],
        "family": "Apiaceae",
        "mena": True,
        "regions": [MED, IRAN],
        "uses": ["Antispasmodic", "Antidiabetic", "Antimicrobial", "Antiobesity"],
    },
    {
        "scientific": "Elettaria cardamomum",
        "synonyms": [],
        "common": ["cardamom", "hail", "hel", "heel"],
        "family": "Zingiberaceae",
        "mena": False,
        "regions": [GLOBAL],
        "uses": ["Antioxidant", "Antimicrobial", "Gastroprotective/Antiulcer", "Antihypertensive"],
    },
    {
        "scientific": "Salvia hispanica",
        "synonyms": [],
        "common": ["chia"],
        "family": "Lamiaceae",
        "mena": False,
        "regions": [GLOBAL],
        "uses": ["Antihyperlipidemic", "Antioxidant", "Antidiabetic"],
    },
    {
        "scientific": "Urtica dioica",
        "synonyms": ["Urtica pilulifera"],
        "common": ["nettle", "stinging nettle", "qurrays", "gazaneh"],
        "family": "Urticaceae",
        "mena": True,
        "regions": [MED, IRAN, MENA],
        "uses": ["Antidiabetic", "Anti-inflammatory", "Antioxidant", "Diuretic", "Antihypertensive"],
    },
    {
        "scientific": "Ecballium elaterium",
        "synonyms": [],
        "common": ["squirting cucumber", "faqqous al-himar", "qatha al-himar"],
        "family": "Cucurbitaceae",
        "mena": True,
        "regions": [MED, LEVANT],
        "uses": ["Anti-inflammatory", "Anticancer/Antitumor", "Antimicrobial", "Hepatoprotective"],
    },
    {
        "scientific": "Achillea millefolium",
        "synonyms": ["Achillea fragrantissima", "Achillea santolina"],
        "common": ["yarrow", "qaysoum", "qaisum", "boomadaran"],
        "family": "Asteraceae",
        "mena": True,
        "regions": [MED, ARABIA, IRAN],
        "uses": ["Anti-inflammatory", "Antioxidant", "Antispasmodic", "Wound healing", "Antidiabetic"],
    },
    {
        "scientific": "Cynara scolymus",
        "synonyms": ["Cynara cardunculus"],
        "common": ["artichoke", "kharshuf", "ardishoki"],
        "family": "Asteraceae",
        "mena": True,
        "regions": [MED, NAFRICA],
        "uses": ["Hepatoprotective", "Antihyperlipidemic", "Antioxidant", "Antidiabetic"],
    },
    {
        "scientific": "Silybum marianum",
        "synonyms": [],
        "common": ["milk thistle", "khurfaysh", "silymarin", "khar maryam"],
        "family": "Asteraceae",
        "mena": True,
        "regions": [MED, IRAN],
        "uses": ["Hepatoprotective", "Antioxidant", "Anticancer/Antitumor", "Anti-inflammatory"],
    },
    {
        "scientific": "Ephedra alata",
        "synonyms": ["Ephedra major", "Ephedra sinica"],
        "common": ["ephedra", "alanda", "ephedra herb", "ma huang"],
        "family": "Ephedraceae",
        "mena": True,
        "regions": [NAFRICA, ARABIA, IRAN],
        "uses": ["Antimicrobial", "Antioxidant", "Anti-inflammatory", "Anticancer/Antitumor"],
    },
    {
        "scientific": "Retama raetam",
        "synonyms": ["Retama monosperma"],
        "common": ["white broom", "retem", "ratam"],
        "family": "Fabaceae",
        "mena": True,
        "regions": [NAFRICA, ARABIA, LEVANT],
        "uses": ["Antidiabetic", "Antihypertensive", "Antioxidant", "Diuretic"],
    },
    {
        "scientific": "Ruta graveolens",
        "synonyms": ["Ruta chalepensis"],
        "common": ["rue", "fijan", "sadhab", "fayjan"],
        "family": "Rutaceae",
        "mena": True,
        "regions": [MED, LEVANT],
        "uses": ["Antispasmodic", "Anti-inflammatory", "Antimicrobial", "Antifertility/Reproductive"],
    },
    {
        "scientific": "Anastatica hierochuntica",
        "synonyms": [],
        "common": ["kaff maryam", "rose of jericho", "hand of mary"],
        "family": "Brassicaceae",
        "mena": True,
        "regions": [ARABIA, NAFRICA, LEVANT],
        "uses": ["Antidiabetic", "Antioxidant", "Uterotonic", "Antimicrobial"],
    },
    {
        "scientific": "Cassia senna",
        "synonyms": ["Senna alexandrina", "Cassia angustifolia"],
        "common": ["senna", "sanamaki", "sena", "cassia"],
        "family": "Fabaceae",
        "mena": True,
        "regions": [ARABIA, NAFRICA],
        "uses": ["Laxative", "Antimicrobial", "Antioxidant", "Hepatoprotective"],
    },
    {
        "scientific": "Ammi visnaga",
        "synonyms": ["Visnaga daucoides"],
        "common": ["khella", "khella", "toothpick weed", "bishop's weed"],
        "family": "Apiaceae",
        "mena": True,
        "regions": [NAFRICA, MED],
        "uses": ["Antispasmodic", "Vasodilator", "Antiasthmatic/Bronchodilator", "Antilithic"],
    },
    {
        "scientific": "Withania somnifera",
        "synonyms": [],
        "common": ["ashwagandha", "winter cherry", "obab", "indian ginseng"],
        "family": "Solanaceae",
        "mena": True,
        "regions": [ARABIA, IRAN, GLOBAL],
        "uses": ["Antidepressant/Anxiolytic", "Immunomodulatory", "Anticancer/Antitumor", "Neuroprotective"],
    },
    {
        "scientific": "Allium sativum",
        "synonyms": [],
        "common": ["garlic", "thoom", "thum", "sir"],
        "family": "Amaryllidaceae",
        "mena": True,
        "regions": [IRAN, MENA, GLOBAL],
        "uses": ["Antihypertensive", "Antihyperlipidemic", "Antimicrobial", "Anticancer/Antitumor", "Antidiabetic"],
    },
    {
        "scientific": "Allium cepa",
        "synonyms": [],
        "common": ["onion", "basal", "piaz"],
        "family": "Amaryllidaceae",
        "mena": True,
        "regions": [IRAN, MENA, GLOBAL],
        "uses": ["Antidiabetic", "Antioxidant", "Antimicrobial", "Antihyperlipidemic"],
    },
    {
        "scientific": "Berberis vulgaris",
        "synonyms": ["Berberis integerrima"],
        "common": ["barberry", "zereshk", "zirishk", "berberis"],
        "family": "Berberidaceae",
        "mena": True,
        "regions": [IRAN, MED],
        "uses": ["Antidiabetic", "Antimicrobial", "Antihyperlipidemic", "Hepatoprotective", "Anticancer/Antitumor"],
    },
    {
        "scientific": "Vitis vinifera",
        "synonyms": [],
        "common": ["grape", "grapevine", "inab", "angoor"],
        "family": "Vitaceae",
        "mena": True,
        "regions": [IRAN, MED, MENA],
        "uses": ["Antioxidant", "Cardioprotective", "Anticancer/Antitumor", "Neuroprotective"],
    },
    {
        "scientific": "Ficus carica",
        "synonyms": [],
        "common": ["fig", "teen", "tin", "anjir"],
        "family": "Moraceae",
        "mena": True,
        "regions": [MED, MENA, LEVANT],
        "uses": ["Antidiabetic", "Antioxidant", "Anticancer/Antitumor", "Hepatoprotective"],
    },
    {
        "scientific": "Juglans regia",
        "synonyms": [],
        "common": ["walnut", "joz", "gerdakan", "gerdoo"],
        "family": "Juglandaceae",
        "mena": True,
        "regions": [IRAN, MED],
        "uses": ["Antidiabetic", "Antioxidant", "Antihyperlipidemic", "Antimicrobial"],
    },
    {
        "scientific": "Pistacia lentiscus",
        "synonyms": ["Pistacia atlantica", "Pistacia vera"],
        "common": ["mastic", "pistachio", "mastic gum", "miski", "botom"],
        "family": "Anacardiaceae",
        "mena": True,
        "regions": [MED, IRAN, LEVANT],
        "uses": ["Gastroprotective/Antiulcer", "Antimicrobial", "Antioxidant", "Anti-inflammatory"],
    },
    {
        "scientific": "Elaeagnus angustifolia",
        "synonyms": [],
        "common": ["russian olive", "oleaster", "senjed", "zaqqum"],
        "family": "Elaeagnaceae",
        "mena": True,
        "regions": [IRAN, MENA],
        "uses": ["Anti-inflammatory", "Analgesic", "Antioxidant", "Anti-arthritic"],
    },
    {
        "scientific": "Nerium oleander",
        "synonyms": [],
        "common": ["oleander", "difla", "defli", "khar zahreh"],
        "family": "Apocynaceae",
        "mena": True,
        "regions": [MED, MENA],
        "uses": ["Anticancer/Antitumor", "Cardioprotective", "Antimicrobial"],
    },
    {
        "scientific": "Calotropis procera",
        "synonyms": [],
        "common": ["apple of sodom", "usher", "ushar", "sodom apple"],
        "family": "Apocynaceae",
        "mena": True,
        "regions": [ARABIA, NAFRICA],
        "uses": ["Anti-inflammatory", "Anticancer/Antitumor", "Antimicrobial", "Wound healing"],
    },
    {
        "scientific": "Rumex vesicarius",
        "synonyms": ["Rumex acetosa"],
        "common": ["bladder dock", "hummayd", "humaid", "sorrel"],
        "family": "Polygonaceae",
        "mena": True,
        "regions": [ARABIA, NAFRICA],
        "uses": ["Antioxidant", "Hepatoprotective", "Analgesic", "Antimicrobial"],
    },
    {
        "scientific": "Salvadora persica",
        "synonyms": [],
        "common": ["arak", "miswak", "siwak", "toothbrush tree"],
        "family": "Salvadoraceae",
        "mena": True,
        "regions": [ARABIA, NAFRICA],
        "uses": ["Antimicrobial", "Anti-inflammatory", "Antioxidant", "Analgesic"],
    },
    {
        "scientific": "Prosopis farcta",
        "synonyms": ["Prosopis juliflora"],
        "common": ["syrian mesquite", "yanboot", "kharnoub"],
        "family": "Fabaceae",
        "mena": True,
        "regions": [ARABIA, IRAN, LEVANT],
        "uses": ["Antidiabetic", "Antioxidant", "Anti-inflammatory", "Antimicrobial"],
    },
    {
        "scientific": "Cyperus rotundus",
        "synonyms": [],
        "common": ["nut grass", "saad", "sooad", "nutsedge"],
        "family": "Cyperaceae",
        "mena": True,
        "regions": [MENA, GLOBAL],
        "uses": ["Anti-inflammatory", "Antidiabetic", "Antioxidant", "Antispasmodic", "Antiobesity"],
    },
    # ---- Common NON-MENA reference plants (mena=False) ------------------------
    {
        "scientific": "Curcuma longa",
        "synonyms": ["Curcuma domestica"],
        "common": ["turmeric", "curcumin", "haldi"],
        "family": "Zingiberaceae",
        "mena": False,
        "regions": [GLOBAL],
        "uses": ["Anti-inflammatory", "Anticancer/Antitumor", "Antioxidant", "Hepatoprotective"],
    },
    {
        "scientific": "Zingiber officinale",
        "synonyms": [],
        "common": ["ginger", "zanjabil", "adrak"],
        "family": "Zingiberaceae",
        "mena": False,
        "regions": [GLOBAL],
        "uses": ["Anti-inflammatory", "Antioxidant", "Antiemetic", "Antidiabetic"],
    },
    {
        "scientific": "Camellia sinensis",
        "synonyms": [],
        "common": ["green tea", "black tea", "tea", "shai"],
        "family": "Theaceae",
        "mena": False,
        "regions": [GLOBAL],
        "uses": ["Antioxidant", "Anticancer/Antitumor", "Antiobesity", "Cardioprotective"],
    },
    {
        "scientific": "Ginkgo biloba",
        "synonyms": [],
        "common": ["ginkgo", "maidenhair tree"],
        "family": "Ginkgoaceae",
        "mena": False,
        "regions": [GLOBAL],
        "uses": ["Neuroprotective", "Antioxidant", "Cardioprotective"],
    },
    {
        "scientific": "Panax ginseng",
        "synonyms": ["Panax quinquefolius"],
        "common": ["ginseng", "korean ginseng"],
        "family": "Araliaceae",
        "mena": False,
        "regions": [GLOBAL],
        "uses": ["Immunomodulatory", "Neuroprotective", "Antidiabetic", "Anticancer/Antitumor"],
    },
    {
        "scientific": "Azadirachta indica",
        "synonyms": [],
        "common": ["neem", "margosa"],
        "family": "Meliaceae",
        "mena": False,
        "regions": [GLOBAL],
        "uses": ["Antimicrobial", "Antidiabetic", "Anti-inflammatory", "Antiparasitic"],
    },
    {
        "scientific": "Moringa oleifera",
        "synonyms": [],
        "common": ["moringa", "drumstick tree", "horseradish tree"],
        "family": "Moringaceae",
        "mena": False,
        "regions": [GLOBAL],
        "uses": ["Antidiabetic", "Antioxidant", "Anti-inflammatory", "Antihyperlipidemic"],
    },
]
